# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    #service_name:
    #    class: AppBundle\Directory\ClassName
    #    arguments: ['@another_service_name', 'plain_value', '%parameter_name%']
    app.logger:
        class:     AppBundle\Service\Logger
        arguments: []

    app.validator:
        class:     AppBundle\Service\Validator
        arguments: ['@app.logger']

    app.converter:
        class:     AppBundle\Service\Converter
        arguments: []

    app.output.command.helper:
        class:     AppBundle\Util\OutputCommandHelper
        arguments: []

    app.data.manager:
        class:     AppBundle\Util\DataManager
        arguments: ['@doctrine.orm.entity_manager', '@app.converter']